def historia_inicial():
    print("--------------------------------------------")
    print("Está chovendo do lado de fora, são quase meia noite.\n") 
    print("Eu não devia ter aceitado jogar roleta-russa com meus colegas da faculdade, eu nem sei como eles conseguiram esse revolver...\n") 
    print("Agora eu estou aqui no banheiro enrolando para não encarar aquilo que eu escolhi para minha vida.\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Eu tô muito longe para pedir ajuda de qualquer pessoa minimamente descente, meu celular foi jogado no vaso pelo Victor, aquele bebado nojento que eu ainda chamo de amigo.\n")  
    print("Eu estou com muito medo de sair daqui, eu só não pulo a janela porque a queda até o chão seria feia.\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Hora de encarar a realidade...\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Eu começo a abrir a porta e aquele cheiro forte de bebida e droga começam a tomar conta do meu nariz.\n") 
    print("Willian alugou uma casa online longe da \"civilização\" para que a galera pudesse fazer o que quisesse livremente, e eu escolhi logo isso...\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Todo mundo sabia que isso aconteceria, mas ninguém estava levando a sério.\n") 
    print("Todas essas pessoas, por causa das drogas que estão ingerindo, vão consentir na morte dos envolvidos e nem percebem.\n") 
    print("Não adianta gritar nem gesticular, é como se, eu podendo falar, ninguém me ouvisse.\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Eu ando até a sala principal da casa. Todo este lugar está uma zona, desde a cozinha até o quintal tem pessoas fazendo algo que afronta até a moral da civilização mais ordinária que já passou pela terra.\n") 
    print("Na sala tem uma mesa redonda com 7 pessoas.\n") 
    print("Uma é o meu oponente, o restante está apenas como plateia que interage com o espetáculo que vai acontecer, mas, estão bebados demais para poderem perceber que, de fato, alguém vai morrer aqui dentro.\n")
    input()
    print("--------------------------------------------")

def explicacao():
    print("--------------------------------------------")
    print("Para esse bando de sádicos que estão aqui aproveitarem mais o jogo, eles decidiram mudar as regras do jogo.\n") 
    print("Ao invés de atirar na cabeça, a pessoa que está com a arma vai decidir se atira nela mesma ou no \"inimigo\".\n") 
    print("O tiro vai ser em alguma parte não letal do corpo para que a vitima jogue por mais tempo.\n") 
    print("E a arma será carregada com bala falsa (de chumbinho) e com bala de verdade, a falsa calsa uma leve dor apenas.\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Se a pessoa com a arma atirar nela mesma, ela pode atirar de novo, só é passada a vez para o outro se a pessoa atirar no oponente dela.\n") 
    print("Há objetos que as pessoas ao redor vão dar para cada um toda vez que a munição acabar.\n") 
    print("Esses objetos ajudam para a pessoa não morrer e para matar mais rápido o outro.\n") 
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Tem um \"ROLO DE CÂMERA\", quem tiver um desse pode usar para saber se na sua vez tem uma bala ou não na arma.\n")  
    print("Outro objeto é a \"FACA\", a pessoa faz um leve corte nela mesma e poderá dar dois tiros de uma vez.\n") 
    print("Será dado também um \"ESPARADRAPO\", isso vai ser usado para parar o sangramento do tiro que você levar.\n")
    print("Será dado um \"AMARRADOR\", a pessoa que for amarrada vai perder a vez.\n") 
    print("Também tem uma faca, com ela você pode se dar um leve corte e poderá dar 2 tiros de uma vez, não que eu jogue duas vezes, mas em quem eu atirar eu vou atirar 2 vezes de uma vez.\n")
    print("E por último, será dado um lápis, ele serve para eu trocar a bala que está na minha vez, se ela for de chumbinho eu troco pela de verdade, se for a de verdade eu troco para a de chumbinho.\n")
    input()
    print("--------------------------------------------")

    print("--------------------------------------------")
    print("Hora de \"aproveitar a vida da forma certa\"...\n")
    input()
    print("--------------------------------------------")
